#deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:5.6
        name: wordpress-deployment
        resources: 
          requests:
            cpu: "50m"
            memory: "100Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc.user-22
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: NU
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
status: {}

#svc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: user-22
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: wordpress
